import datetime

from langchain_core.prompts import PromptTemplate

from llm import get_llm_sambanova
from utils import load_prompt

def gen_report(compA: str, compB: str, reco: str, main: str) -> str:
    super_model = get_llm_sambanova()

    prompt = PromptTemplate.from_template(template=load_prompt(f'gen_report_prompt.txt'))
    prompt = prompt.invoke({'compA': compA, 'compB': compB, 'reco': reco, 'main': main, 'date': datetime.date.today().strftime('%B %d, %Y')})
    prompt = prompt.to_string()
    print(prompt)

    answer = super_model.invoke(prompt)
    answer = answer.content
    print(answer)
    return answer

if __name__ == '__main__':
    # test usage
    compA = "Here's what I found for MICROSOFT CORP based on their latest financial statements:\n\n**1. Revenue**\n\nThe revenue for Microsoft Corp was $245,122 million for the year ended June 30, 2024, and $211,915 million for the year ended June 30, 2023, showing a 16% increase. For the three months ended September 30, 2024, the revenue was $65,585 million, and for the three months ended September 30, 2023, it was $56,517 million, also showing a 16% increase.\n\nThe revenue growth trend is consistently increasing, with a 16% increase in both the yearly and quarterly comparisons.\n\n**2. Net Income**\n\nThe net income for Microsoft Corp was $88,136 million for the year ended June 30, 2024, and $72,361 million for the year ended June 30, 2023, showing a 22% increase. For the three months ended September 30, 2024, the net income was $24,667 million, and for the three months ended September 30, 2023, it was $22,291 million, showing an 11% increase.\n\nThe net income growth is consistently increasing, with a 22% increase in the yearly comparison and an 11% increase in the quarterly comparison.\n\n**3. Earnings Per Share (EPS)**\n\nThe diluted EPS for Microsoft Corp was $11.80 for the year ended June 30, 2024, and $9.68 for the year ended June 30, 2023, showing a 22% increase. For the three months ended September 30, 2024, the diluted EPS was $3.30, and for the three months ended September 30, 2023, it was $2.99, showing a 10% increase.\n\nThe EPS trend is consistently increasing, with a 22% increase in the yearly comparison and a 10% increase in the quarterly comparison.\n\nFinancial statements used:\n\n- MICROSOFT CORP - FORM 10-K - 2024-07-30 (https://www.sec.gov/ix?doc=/Archives/edgar/data/0000789019/000095017024087843/msft-20240630.htm)\n- MICROSOFT CORP - FORM 10-Q - 2024-10-30 (https://www.sec.gov/ix?doc=/Archives/edgar/data/0000789019/000095017024118967/msft-20240930.htm)"
    compB = "Here's what I found for NVIDIA Corporation based on their latest financial statements:\n\n**1. Revenue**\n\nThe revenue for NVIDIA Corporation for the three months ended October 27, 2024, was $35,082 million, and for the nine months ended October 27, 2024, was $91,166 million. In comparison, the revenue for the three months ended October 29, 2023, was $18,120 million, and for the nine months ended October 29, 2023, was $38,819 million.\n\nThe revenue growth trend shows an increase of 93.5% for the three months ended October 27, 2024, compared to the same period in 2023, and an increase of 134.8% for the nine months ended October 27, 2024, compared to the same period in 2023.\n\nThe revenue by reportable segments for the three months ended October 27, 2024, was $31,036 million for Compute & Networking and $4,046 million for Graphics. For the nine months ended October 27, 2024, the revenue by reportable segments was $80,157 million for Compute & Networking and $11,009 million for Graphics.\n\n**2. Net Income**\n\nThe net income for NVIDIA Corporation for the three months ended October 27, 2024, was $19,309 million, and for the nine months ended October 27, 2024, was $50,789 million. In comparison, the net income for the three months ended October 29, 2023, was $9,243 million, and for the nine months ended October 29, 2023, was $17,475 million.\n\nThe net income growth shows an increase of 108.7% for the three months ended October 27, 2024, compared to the same period in 2023, and an increase of 190.5% for the nine months ended October 27, 2024, compared to the same period in 2023. The net income appears to be consistently increasing over the periods presented.\n\n**3. Earnings Per Share (EPS)**\n\nThe EPS for NVIDIA Corporation for the three months ended October 27, 2024, was $0.79 (basic) and $0.78 (diluted), and for the nine months ended October 27, 2024, was $2.07 (basic) and $2.04 (diluted). In comparison, the EPS for the three months ended October 29, 2023, was $0.37 (basic and diluted), and for the nine months ended October 29, 2023, was $0.71 (basic) and $0.70 (diluted).\n\nThe EPS trend shows an increase of 113.5% (basic) and 110.8% (diluted) for the three months ended October 27, 2024, compared to the same period in 2023, and an increase of 191.5% (basic) and 191.4% (diluted) for the nine months ended October 27, 2024, compared to the same period in 2023.\n\nFinancial statements used:\n\n* NVIDIA CORP - FORM 10-Q - 2024-11-20 (https://www.sec.gov/ix?doc=/Archives/edgar/data/0001045810/000104581024000316/nvda-20241027.htm)\n* NVIDIA CORP - FORM 10-Q - 2024-08-28 (https://www.sec.gov/ix?doc=/Archives/edgar/data/0001045810/000104581024000264/nvda-20240728.htm)"
    reco = "Based on the provided earnings performance details for Microsoft (MSFT) and NVIDIA (NVDA), here's a comparison of the two stocks and a recommendation:\n\n**Revenue Growth:**\nMSFT: 16% increase in both yearly and quarterly comparisons\nNVDA: 93.5% increase in quarterly comparison and 134.8% increase in nine-month comparison\n\n**Net Income Growth:**\nMSFT: 22% increase in yearly comparison and 11% increase in quarterly comparison\nNVDA: 108.7% increase in quarterly comparison and 190.5% increase in nine-month comparison\n\n**Earnings Per Share (EPS) Growth:**\nMSFT: 22% increase in yearly comparison and 10% increase in quarterly comparison\nNVDA: 113.5% increase in quarterly comparison and 191.5% increase in nine-month comparison\n\nNVIDIA's revenue, net income, and EPS growth rates significantly outpace those of Microsoft. NVIDIA's strong growth is driven by its dominant position in the AI and graphics processing markets, which are experiencing rapid expansion.\n\n**Recommendation:**\nBased on the earnings performance, NVIDIA (NVDA) appears to be a more attractive investment opportunity than Microsoft (MSFT) at this time. NVIDIA's exceptional growth rates, driven by its leadership in AI and graphics processing, make it a compelling choice for investors seeking high-growth potential.\n\nHowever, it's essential to consider the following factors before making an investment decision:\n\n1. Valuation: NVIDIA's stock price may be higher due to its exceptional growth rates, which could impact its valuation.\n2. Industry trends: The AI and graphics processing markets are rapidly evolving, and NVIDIA's dominance may be challenged by emerging competitors.\n3. Risk tolerance: Investors should assess their risk tolerance and consider the potential volatility associated with investing in high-growth stocks like NVIDIA.\n\nUltimately, a thorough analysis of both companies' financials, industry trends, and competitive landscapes is necessary to make an informed investment decision."
    main = "Based on earnings performance, **NVDA** appears to be a more attractive investment opportunity than MSFT, driven by its exceptional growth rates in revenue, net income, and EPS, and its dominant position in the rapidly expanding AI and graphics processing markets."
    html = gen_report(compA, compB, reco, main)
    pass
